[google_service_account]
type = "service_account"
project_id = "varsitiesdata"
private_key_id = "8933d4dc618ae8038137d22059a27a16197bd7ef"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC3Swf+9Qzw2i9Y
ZLSZ87mVvovVCJFhNaaJ1yLnmMWSq9J34oyy+1H5QQ1sMcpWdWL4cdSVWIjT5JCQ
pUEq/l11vFFcocn+XKVaysrz8YMUjhzV3vWq4eX4frdD5yRP9DPLhBQNfT63lSQd
qYGNfy7S453MVWG8UHfK5T7jb3bWjV5yyz9oBHu754ir5CmMYZ90dW0B0fvaQIIr
vQ8PpArVewRckJDJpGgTfsp4lbfXFo4T20EGOQd0mTj9oB9iK393/u9PhdPme9Ef
uHdSc2aH+1MWkySCSjiBrjChxnhc+f5dKl2+okFwvk3wWci7qerCDk87PZpCz+DZ
Pt1OknJjAgMBAAECggEADdGGy0u/Ni3vfCsEy0cqz9AbQQF8hbHNRJQRv23EQMAF
GzZbDtKlW0odEHHv2V/P3n96cZNIpteS/Iyw4o8QYw7CVYj5rlxet6m/7kSKx33F
TRcaOfqo403uVBy0yfWqV/wKT6Vdw+pnBs4fhG2OYqYitePJUrCrBK1kIIe9PlnY
8X37hb/Gwdz7XioEWuM5X7qIy2BCSomyCvGYAi4xnH9nbfP5Vfyalyyu4QeSTxK2
5f86/2Tgh59d/+AQcwGA+a3YuA5HVrhCWeAKnBdR2KQ9XtdBp88D/8mpnbA1Q8Gf
JgUM79n6cvesj7iSQTHQzWuxNIc8CoaZRpI2HlymmQKBgQDuVw/BOitOeoy4dC4K
0Sj7Tm7EuGnN9WryhmY8Un/JB0kcjZyR6pPOdnNr4mlZ2k/fUS60QmNt4dI4RHvB
xLFVH8QT6QzYIVhN8mFTEJb0IyIkJtFz6j9YF+ho+6R5D+ek5xcP+HhQilkeZU/Q
AqRkWPcyVA3G/yrpp8yBiEgrywKBgQDE39B5+GEFlcoCdcxSK2ATIEVXZwhcCQ1i
tUGHzYeuEVOhiARuaOZF+zWPUrcWfr1OU0Tl4r9VNLl/ynzNcQYjuGm1w1s7Hs4N
N7MwPIuYgSax9Ykrp8R9ZCavHVIbsk2aShWaZLvQXTjmuae+aRrWcN8EyAHPxUg/
ZziEPtYwyQKBgQDswhNmcTA/30EWomJyYGADdGBYjpCcBaTdkmDQn2tM+S3JbWsR
ECMPv17c1qasmU8qmWx5qFE5AFBhkLYXQBqgYtPWq3UU5drgY1wGtb4eeyAZJW5/
ZTzTd7xpPUCe+gu0JdMlDEAIUcZBiYaFLXq8LBwzJIgjG6s3PHbMXeLDjQKBgBBA
cZM//7JYVR6y3rUBw6KQjWjTposCbEpzr/8n5kVmRMMW2VbL7gZk4Fz+dQK0X6gx
k4RunWDJQ27bJkZHSDx2orNQdx2AQ34v1OjsdpGWR711CWfDJ6M6Oz9FalvC8kkE
SJhALIjcyS+yr7g2MPL2ylI4uH2QSZCCUtYH4eKRAoGBAMvFYYinTM8gvDl5h4B8
A5lqk3QyKUxyfO4zkzrJGGJ9UoE55TaYKS1KZz1Q+s8fld0LkOY4QxYZjlRgTkk2
kdQJ/g9sCcNVMk8Q0uiw/SRYL4oQJ65AwzvA+Zt6euyY/8fVTWKxwBSitGwuqc1U
srXcgMIxLi5bQMPGuMzYJPJY
-----END PRIVATE KEY-----"""
client_email = "jahid-531@varsitiesdata.iam.gserviceaccount.com"
client_id = "117041841204356252522"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/jahid-531@varsitiesdata.iam.gserviceaccount.com"
